### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by JagaRamesh** [ww1010/intro-data-capstone-biodiversity#2]
Excellent job explaining the analysis and the outcome in the document.

The powerpoint slides are very neat and inviting!
For "Endangerment of species" analysis, it is good to add the "Objective" slide. I would suggest to add the slide to discuss about chi-square test results of Mammals Vs Birds, Mammals Vs Reptiles. The conclusion is correct, but the recommendation to conservationists would be to focus on highly endangered species (Mammals & Birds).

The matplotlib plots are neat with proper title, xlabel and ylabel defined. It would be good to use the plots as a part of the analysis rather than showing them in the last two slides.

One recommendation in "Foot and mouth disease analysis" is to add an add an "Objective" & "Data observation" slide before going into the sample size determination. Also question about "No of weeks needed to observe sheep" is not answered. I have created a separate issue for the same.

Overall Good job!!! KEEP IT UP.

**Comment by ww1010** [comment]
Hi Jaga,
thank you very much for reviewing the project and for your feedback! 
I updated the issues a I hope, that I understood all of you recommendations right! 
There is a new file "Slide Desk V2" with the improvements added to this repository.
